#!/usr/bin/env bash


create_activate_script() {
	cat > $1/activate <<-EOT
		#!/usr/bin/env bash
		export GOPATH=$1/env
		export PATH=\$GOPATH/bin:\$PATH
	EOT
	chmod a+x $1/activate
}


create_deactivate_script() {
	cat > $1/deactivate <<-EOT
		#!/usr/bin/env bash
		export PATH=\$(echo \$PATH | sed "s|\$GOPATH/bin:||g")
		unset GOPATH
	EOT
	chmod a+x $1/activate
}



create_env() {
	ENV_PATH=$GOENVPATH/$1
	if [[ ! -d $ENV_PATH ]]; then
		echo "Creating environment $1"
		mkdir -p $ENV_PATH/env
		create_activate_script $ENV_PATH
		create_deactivate_script $ENV_PATH
	else
		echo "$1 already exists"
		exit 1
	fi
}


activate_env() {
	echo "Activating $1"
	source $GOENVPATH/$1/activate
}


deactivate_env() {
	echo "Deactivating $1"
	source $GOENVPATH/$1/deactivate
}


display_help() {
	echo "Usage: $0 {create|activate|deactivate|delete} name" >&2
	echo
}

test_reqs() {
	if [ -z $GOENVPATH ]; then
		echo "GOENVPATH not set"
		exit 1
	fi

	if [ "$#" -ne 2 ]; then
		echo "Illegal number of parameters"
		exit 1
	fi
}

test_reqs $@

case "$1" in
	create)
		create_env $2
		;;
	activate)
		activate_env $2
		;;
	deactivate)
		deactivate_env $2
		;;
	*)
		display_help

		exit 1
		;;
esac
